const fs = require('fs'), vm = require('vm'), assert = require('assert');
const src = fs.readFileSync('docs/app.js', 'utf8');
const ctx = {}; vm.createContext(ctx);
vm.runInContext(src.slice(src.indexOf('const draftAvailableSources ='), src.indexOf('function renderDraftDay(')), ctx);
const consensus = {pid:'c',name:'Consensus Leader',cons_rank:4};
const custom = {pid:'m',name:'Custom Leader',board_no:1};
const v = {rail:{club:{abbr:'GB'},year:2027},best:[consensus],board:[custom],has_custom_board:false,read:'Saved board analysis'};
let r = ctx.draftAvailableView(v);
assert.equal(r.source,'consensus'); assert.equal(r.top.pid,'c');
assert.ok(r.read.includes('Consensus Leader')); assert.ok(r.note.includes('scouts'));
assert.ok(r.note.includes('manual Draft button'));
assert.ok(r.note.includes('automatic picks use your saved priorities'));
r = ctx.draftAvailableView({...v,has_custom_board:true});
assert.equal(r.source,'mine'); assert.equal(r.top.pid,'m');
vm.runInContext("draftAvailableSources.set('GB:2027','mine')",ctx);
r = ctx.draftAvailableView(v);
assert.equal(r.source,'mine'); assert.ok(r.note.includes('No custom order')); assert.ok(r.read.includes('scouts'));
vm.runInContext("draftAvailableSources.set('GB:2027','consensus')",ctx);
r = ctx.draftAvailableView({...v,has_custom_board:true});
assert.equal(r.top.pid,'c');
assert.equal(ctx.draftAvailableView({...v,best:[]}).top,null);
assert.equal(ctx.draftAvailableView({...v,rail:{club:{abbr:'GB'},year:2028},has_custom_board:true}).source,'mine');
console.log('Passed: consensus/custom defaults, selector preference, matching top prospect and analysis, empty board, new-season reset');
