const fs=require('fs'),vm=require('vm'),assert=require('assert');
const src=fs.readFileSync('docs/app.js','utf8');
function el(tag,attrs={},...kids){return {tag,attrs,kids,dataset:{pid:attrs['data-pid']},classList:{toggle(){}},style:{},append(...x){this.kids.push(...x)},replaceChildren(...x){this.kids=x},querySelectorAll(){return this.kids.filter(x=>x?.attrs?.['data-pid'])},focus(){},addEventListener(name,fn){this[name]=fn},remove(){this.removed=true}}}
const nodes={page:el('main'),crumb:el('span'),nav:{querySelectorAll:()=>[]}};
const body=el('body');
const c={el,$:s=>nodes[s.slice(1)],renderRail(){},secondRow(){},clubNav(){return[]},scheduleSeasonPicker(){return el('select')},location:{hash:''},document:{body},teamTheme:t=>({base:t.color,accent:t.accent})};vm.createContext(c);
vm.runInContext(src.slice(src.indexOf('function reportBoard'),src.indexOf('// the roster\'s development')),c);
vm.runInContext(src.slice(src.indexOf('function renderRegression'),src.indexOf("// A TEAM'S SCHEDULE")),c);
const row=(pid,name)=>({pid,name,pos:'QB',age:35,no:10,before:88,after:85,delta:-3,still_here:true,cols:[{title:'Passing',rows:[{key:'power',label:'Throw Power',v:80,delta:-4},{key:'awareness',label:'Awareness',v:88,delta:1},{key:'speed',label:'Speed',v:75,delta:0}]}]});
c.renderRegression({rail:{},club:{abbr:'GB',name:'Green Bay',color:'#203731',accent:'#ffb612'},year:2026,years:[2026],hit:2,total_lost:6,rows:[row('1','First'),row('2','Second')]});
const board=nodes.page.kids[0], table=board.kids[2].kids[0];
const second=table.kids[2];second.kids[5].kids[0].attrs.onclick();
const popup=body.kids[0], dialog=popup.kids[0];
assert.equal(dialog.attrs.role,'dialog');
assert.equal(dialog.attrs['aria-label'],'Second rating changes');
const text=JSON.stringify(dialog.kids);
assert.ok(text.includes('84 → 80'));
assert.ok(text.includes('87 → 88'));
assert.ok(!text.includes('Speed'));
popup.keydown({key:'Escape'}); assert.equal(popup.removed,true);
console.log('Regression: selected player popup, historical losses/gains, unchanged-rating filtering, and dismissal passed');
